### ISSUE TITLE
how to use this visualizer

### ISSUE THREAD

**Issue by vip32** [brentkrueger/VisualStudio2015PackageVisualizer#1]
first of all, thx for making the effort to port this from older vs.

however it is not present under: tools > package manager
i can find it when doing a search (ctrl-q), but then i get an empty diagram. how to show the nuget dependencies?

**Comment by brentkrueger** [comment]
Hello,

After building the solution, there will be a PackageVisualizer.vsix file in the bin. Use that to install the extension for VS2015. Once it is complete, you'll have to restart visual studio. After that is done, the extension should show up directly under Tools as "Nuget Package Visualizer". This is how you use the extension. Once you run the extension/command, you will get an output file with your results called NugetVisualizerOutput.dgml
